# Generated by Django 5.2.9 on 2025-12-07 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('condo', 'Condo')], max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('location', models.CharField(max_length=100)),
                ('max_guests', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amenities', models.JSONField(default=list)),
            ],
        ),
    ]
