# Generated by Django 5.2.9 on 2025-12-07 06:46

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at'], 'verbose_name': 'Property Listing', 'verbose_name_plural': 'Property Listings'},
        ),
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when listing was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether the property is available for booking'),
        ),
        migrations.AddField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when listing was last updated'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text='List of amenities (e.g., WiFi, Pool, Parking)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(help_text='Detailed description of the property'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(help_text='Property location (city, country)', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='max_guests',
            field=models.PositiveIntegerField(help_text='Maximum number of guests', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, help_text='Price per night in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('condo', 'Condo')], help_text='Type of property', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text='Property title/name', max_length=200),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['property_type'], name='hotel_manag_propert_03914f_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['location'], name='hotel_manag_locatio_4d7c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price_per_night'], name='hotel_manag_price_p_a96400_idx'),
        ),
    ]
